### ISSUE TITLE
Discussion regarding release 1.0

### ISSUE THREAD

**Issue by yamut** [yamut/string-reverse#7]
I think we've moved past the proof of concept phase and are ready to release version 1.

**Comment by yamut** [comment]
@bill-c-martin, thoughts?

**Comment by bill-c-martin** [comment]
Has it gone through performance testing? You will notice the phpunit test I committed for palindromes uses the # of days since the epoch to come up with the string length of the palindrome, and therefore, now takes a bit of a long time to complete lol. However, that actually makes it more enterprise grade, because we know it can handle absurdly long palindromes.

**Comment by yamut** [comment]
Excellent point. I will add a performance test to the unit tests.

**Comment by yamut** [comment]
#9
